#!/usr/bin/env python3

import csv
import json
import re
from pathlib import Path

import matplotlib.pyplot as plt


# =============================================================================
# Paths
# =============================================================================

INTERMEDIATE_DIR = Path("logs/intermediate")

CACHE_FILE = Path("logs/benchmark_cache.json")

COMBINED_FILE = Path(
    "logs/combined_latency_throughput.csv"
)

GRAPH_FILE = Path(
    "logs/latency_vs_throughput.png"
)


FILE_PATTERN = re.compile(
    r"client_.+_(\d+)conc\.csv$"
)


# =============================================================================
# Cache
# =============================================================================

def load_cache():
    if not CACHE_FILE.exists():
        return {"files": {}}

    try:
        with CACHE_FILE.open("r") as f:
            return json.load(f)

    except (OSError, json.JSONDecodeError):
        print("Invalid cache; rebuilding.")
        return {"files": {}}


def save_cache(cache):
    CACHE_FILE.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    with CACHE_FILE.open("w") as f:
        json.dump(
            cache,
            f,
            indent=2,
        )


# =============================================================================
# Parse one benchmark CSV
# =============================================================================

def read_result_file(path):
    with path.open("r", newline="") as f:
        reader = csv.DictReader(f)

        row = next(reader, None)

    if row is None:
        raise ValueError(
            "CSV contains no benchmark data"
        )

    required = [
        "run_duration_s",
        "concurrency",
        "generated_requests",
        "completed_requests",
        "completed_within_run",
        "total_latency_ns",
        "average_latency_us",
        "request_throughput_rps",
        "message_throughput_mps",
    ]

    missing = [
        field
        for field in required
        if field not in row
    ]

    if missing:
        raise ValueError(
            "CSV was generated by the old benchmark "
            f"and is missing: {missing}"
        )

    return {
        "run_duration_s":
            float(row["run_duration_s"]),

        "concurrency":
            int(row["concurrency"]),

        "generated_requests":
            int(row["generated_requests"]),

        "completed_requests":
            int(row["completed_requests"]),

        "completed_within_run":
            int(row["completed_within_run"]),

        "total_latency_ns":
            int(row["total_latency_ns"]),

        "average_latency_us":
            float(row["average_latency_us"]),

        "request_throughput_rps":
            float(row["request_throughput_rps"]),

        "message_throughput_mps":
            float(row["message_throughput_mps"]),
    }


# =============================================================================
# Cached reading
# =============================================================================

def get_result(path, cache):
    stat = path.stat()

    key = str(path.resolve())

    size = stat.st_size
    mtime_ns = stat.st_mtime_ns

    cached = cache["files"].get(key)

    if cached is not None:
        if (
            cached.get("size") == size
            and
            cached.get("mtime_ns") == mtime_ns
        ):
            return cached["result"], True

    result = read_result_file(path)

    cache["files"][key] = {
        "size": size,
        "mtime_ns": mtime_ns,
        "result": result,
    }

    return result, False


# =============================================================================
# Collect all intermediate files
# =============================================================================

def collect_results():
    cache = load_cache()

    grouped = {}

    parsed_count = 0
    cached_count = 0

    existing_files = set()

    files = sorted(
        INTERMEDIATE_DIR.glob(
            "client_*_*conc.csv"
        )
    )

    if not files:
        raise RuntimeError(
            f"No benchmark CSVs found in "
            f"{INTERMEDIATE_DIR}"
        )

    for path in files:
        match = FILE_PATTERN.match(
            path.name
        )

        if match is None:
            continue

        absolute_path = str(
            path.resolve()
        )

        existing_files.add(
            absolute_path
        )

        try:
            result, was_cached = (
                get_result(
                    path,
                    cache,
                )
            )

        except Exception as exc:
            print(
                f"Skipping {path}: {exc}"
            )
            continue

        if was_cached:
            cached_count += 1
        else:
            parsed_count += 1

        concurrency = (
            result["concurrency"]
        )

        grouped.setdefault(
            concurrency,
            [],
        ).append(result)

    # /*
    #  * Remove stale cache entries.
    #  */

    stale = [
        key
        for key in cache["files"]
        if key not in existing_files
    ]

    for key in stale:
        del cache["files"][key]

    save_cache(cache)

    print(
        f"CSV files: "
        f"{cached_count} cached, "
        f"{parsed_count} parsed"
    )

    return grouped


# =============================================================================
# Aggregate clients belonging to the same concurrency
# =============================================================================

def aggregate(grouped):
    combined = []

    for concurrency in sorted(grouped):
        clients = grouped[concurrency]

        client_count = len(clients)

        completed_within_run = sum(
            client["completed_within_run"]
            for client in clients
        )

        total_latency_ns = sum(
            client["total_latency_ns"]
            for client in clients
        )

        aggregate_throughput = sum(
            client["request_throughput_rps"]
            for client in clients
        )

        aggregate_message_throughput = sum(
            client["message_throughput_mps"]
            for client in clients
        )

        generated_requests = sum(
            client["generated_requests"]
            for client in clients
        )

        completed_requests = sum(
            client["completed_requests"]
            for client in clients
        )

        # /*
        #  * IMPORTANT:
        #  *
        #  * Do NOT average client averages.
        #  *
        #  * Compute the weighted average across every
        #  * completed request from every client.
        #  */

        if completed_within_run == 0:
            average_latency_us = 0.0

        else:
            average_latency_us = (
                total_latency_ns
                / completed_within_run
                / 1000.0
            )

        combined.append({
            "concurrency":
                concurrency,

            "client_count":
                client_count,

            "total_concurrency":
                concurrency * client_count,

            "generated_requests":
                generated_requests,

            "completed_requests":
                completed_requests,

            "completed_within_run":
                completed_within_run,

            "total_latency_ns":
                total_latency_ns,

            "average_latency_us":
                average_latency_us,

            "request_throughput_rps":
                aggregate_throughput,

            "message_throughput_mps":
                aggregate_message_throughput,
        })

    return combined


# =============================================================================
# Combined CSV
# =============================================================================

def write_combined_csv(results):
    COMBINED_FILE.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    fields = [
        "concurrency",
        "client_count",
        "total_concurrency",
        "generated_requests",
        "completed_requests",
        "completed_within_run",
        "total_latency_ns",
        "average_latency_us",
        "request_throughput_rps",
        "message_throughput_mps",
    ]

    with COMBINED_FILE.open(
        "w",
        newline="",
    ) as f:
        writer = csv.DictWriter(
            f,
            fieldnames=fields,
        )

        writer.writeheader()
        writer.writerows(results)


# =============================================================================
# Plot latency vs throughput
# =============================================================================

def plot_results(results):
    if not results:
        raise RuntimeError(
            "No valid benchmark points found"
        )

    throughput = [
        result["request_throughput_rps"]
        for result in results
    ]

    latency = [
        result["average_latency_us"]
        for result in results
    ]

    plt.figure(
        figsize=(9, 6)
    )

    plt.plot(
        throughput,
        latency,
        marker="o",
        linewidth=2,
    )


     # Label every point with the PER-CLIENT
     # concurrency that produced it.

    for result in results:
        x = result[
            "request_throughput_rps"
        ]

        y = result[
            "average_latency_us"
        ]

        concurrency = result[
            "concurrency"
        ]

        plt.annotate(
            f"C={concurrency}",
            (x, y),
            xytext=(6, 6),
            textcoords="offset points",
        )

    plt.xlabel(
        "Aggregate throughput (requests/sec)"
    )

    plt.ylabel(
        "Average latency (µs)"
    )

    plt.title(
        "Reactor: Average Latency vs Throughput"
    )

    plt.grid(
        True,
        linestyle="--",
        alpha=0.4,
    )

    plt.ticklabel_format(
        axis="x",
        style="plain",
    )

    plt.tight_layout()

    GRAPH_FILE.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    plt.savefig(
        GRAPH_FILE,
        dpi=200,
    )

    print(
        f"Graph written to: {GRAPH_FILE}"
    )

    plt.show()


# =============================================================================
# Main
# =============================================================================

def main():
    grouped = collect_results()

    results = aggregate(
        grouped
    )

    print()
    print(
        "Latency vs Throughput"
    )
    print(
        "-" * 90
    )

    for result in results:
        print(
            f"C={result['concurrency']:>5} | "
            f"clients={result['client_count']:>3} | "
            f"throughput="
            f"{result['request_throughput_rps']:>15,.2f} req/s | "
            f"avg latency="
            f"{result['average_latency_us']:>12,.2f} us"
        )

    print()

    write_combined_csv(
        results
    )

    print(
        f"Combined CSV written to: "
        f"{COMBINED_FILE}"
    )

    plot_results(
        results
    )


if __name__ == "__main__":
    main()
