use crate::common::{Msg, PAYLOAD_SIZE, Request};

use rand::Rng;
use reactor_actor::codec::BincodeCodec;
use reactor_actor::{BehaviourBuilder, RouteTo, RuntimeCtx, SendErrAction};
use serde::Deserialize;

use std::collections::HashMap;
use std::fs::File;
use std::io::{BufWriter, Write};
use std::time::{Duration, Instant};

#[derive(Clone, Deserialize)]
pub struct Workload {
    #[serde(default)]
    pub concurrency: usize,

    #[serde(default)]
    pub run_duration: u64,
}

pub struct WorkloadConfig {
    pub concurrency: usize,
    pub run_duration: Duration,
}

impl WorkloadConfig {
    fn new(workload: Workload) -> Self {
        Self {
            concurrency: workload.concurrency,
            run_duration: Duration::from_secs(workload.run_duration),
        }
    }
}

/*
 * No shared state.
 * No atomics.
 *
 * RequestFactory is used independently by:
 *
 *   1. WorkloadIterator to seed the initial concurrency window.
 *   2. Processor to generate replacement requests.
 *
 * All benchmark accounting is owned exclusively by Processor.
 */
struct RequestFactory {
    client_addr: String,
}

impl RequestFactory {
    fn new(client_addr: String) -> Self {
        Self { client_addr }
    }

    fn generate_request(&self) -> Msg {
        Msg::Request(Request {
            client_addr: self.client_addr.clone(),

            /*
             * Exactly 128 bytes of application payload.
             *
             * The complete serialized network message will naturally
             * be larger because it also contains client_addr,
             * enum/framing metadata, etc.
             */
            payload: [0u8; PAYLOAD_SIZE],
        })
    }
}

/*
 * Generator only fills the initial closed-loop window.
 *
 * After these `concurrency` requests have been generated, it stops.
 *
 * Every subsequent request is generated by Processor when a
 * response arrives.
 */
pub struct WorkloadIterator {
    remaining_initial_requests: usize,
    request_factory: RequestFactory,
}

impl WorkloadIterator {
    pub fn new(client_addr: String, concurrency: usize) -> Self {
        Self {
            remaining_initial_requests: concurrency,
            request_factory: RequestFactory::new(client_addr),
        }
    }
}

impl Iterator for WorkloadIterator {
    type Item = Msg;

    fn next(&mut self) -> Option<Self::Item> {
        if self.remaining_initial_requests == 0 {
            return None;
        }

        self.remaining_initial_requests -= 1;

        Some(self.request_factory.generate_request())
    }
}

/*
 * All benchmark state lives here.
 *
 * Processor is single-threaded from the benchmark's perspective,
 * so these are ordinary integers.
 *
 * No Arc.
 * No Mutex.
 * No AtomicU64.
 * No AtomicBool.
 */
struct Processor {
    start_time: Option<Instant>,
    client_id: String,
    config: WorkloadConfig,

    request_factory: RequestFactory,

    generated_requests: u64,
    completed_requests: u64,
    completed_within_run: u64,

    outstanding_requests: usize,

    generation_done: bool,
    results_flushed: bool,
}

impl Processor {
    fn handle_response(&mut self) -> Vec<Msg> {
        /*
         * A response means one currently outstanding request
         * has completed.
         */
        self.completed_requests += 1;

        debug_assert!(
            self.outstanding_requests > 0,
            "Received a response with no outstanding requests"
        );

        if self.outstanding_requests > 0 {
            self.outstanding_requests -= 1;
        }

        /*
         * Measurement interval is still active.
         *
         * Refill the just-released closed-loop slot immediately.
         */
        let start_time = self.start_time.unwrap();
        if start_time.elapsed() < self.config.run_duration {
            self.completed_within_run += 1;

            self.generated_requests += 1;
            self.outstanding_requests += 1;

            return vec![self.request_factory.generate_request()];
        }

        /*
         * Measurement interval has ended.
         *
         * No more replacement requests are generated.
         * From this point onward outstanding_requests can only
         * decrease.
         */
        if !self.generation_done {
            self.generation_done = true;

            println!(
                "LOAD GENERATION COMPLETED: {} requests outstanding",
                self.outstanding_requests
            );
        }

        /*
         * Last in-flight response has arrived.
         */
        if self.outstanding_requests == 0 {
            println!("REQUESTS DRAINED.");
        }

        vec![]
    }

    fn flush_results_once(&mut self) {
        if self.results_flushed {
            return;
        }

        self.results_flushed = true;

        if let Err(e) = flush_results(
            &self.client_id,
            &self.config,
            self.generated_requests,
            self.completed_requests,
            self.completed_within_run,
        ) {
            eprintln!(
                "Failed to flush results for client {}: {}",
                self.client_id, e
            );
        }
    }
}

impl Drop for Processor {
    fn drop(&mut self) {
        /*
         * Normally results are written when the actor gets externally
         * stopped.
         */
        self.flush_results_once();
    }
}

impl reactor_actor::ActorProcess for Processor {
    type IMsg = Msg;
    type OMsg = Msg;

    fn process(&mut self, input: Self::IMsg) -> Vec<Self::OMsg> {
        match input {
            /*
             * Requests entering Processor are the initial requests
             * produced by WorkloadIterator.
             *
             * Replacement requests produced by handle_response()
             * leave Processor directly as outputs and therefore do
             * NOT pass through this branch again.
             */
            Msg::Request(request) => {
                // Assigning start_time, the very first a request is launched
                if self.start_time.is_none() {
                    self.start_time = Some(Instant::now());
                }

                self.generated_requests += 1;
                self.outstanding_requests += 1;

                vec![Msg::Request(request)]
            }

            Msg::Response(_) => self.handle_response(),
        }
    }
}

struct Sender {
    server: String,
}

impl reactor_actor::ActorSend for Sender {
    type OMsg = Msg;

    async fn before_send<'a>(&'a mut self, output: &Self::OMsg) -> RouteTo<'a> {
        match output {
            Msg::Request(_) => RouteTo::from(self.server.as_str()),

            Msg::Response(_) => {
                panic!("Client tried to send a response message")
            }
        }
    }
}

impl Sender {
    fn new(server: String) -> Self {
        Self { server }
    }
}

fn flush_results(
    client_id: &str,
    config: &WorkloadConfig,
    generated_requests: u64,
    completed_requests: u64,
    completed_within_run: u64,
) -> std::io::Result<()> {
    let filename = format!(
        "logs/intermediate/client_{}_{}conc.csv",
        client_id, config.concurrency
    );

    let mut writer = BufWriter::new(File::create(filename)?);

    let request_throughput_rps = completed_within_run as f64 / config.run_duration.as_secs_f64();

    /*
     * Each completed request/response operation consists of:
     *
     *     Client -> Server : Request
     *     Server -> Client : Response
     *
     * Therefore two application messages per completed operation.
     */
    let message_throughput_mps = request_throughput_rps * 2.0;

    writeln!(
        writer,
        "run_duration_s,concurrency,generated_requests,completed_requests,completed_within_run,request_throughput_rps,message_throughput_mps"
    )?;

    writeln!(
        writer,
        "{},{},{},{},{},{},{}",
        config.run_duration.as_secs(),
        config.concurrency,
        generated_requests,
        completed_requests,
        completed_within_run,
        request_throughput_rps,
        message_throughput_mps,
    )?;

    writer.flush()
}

pub async fn client(
    ctx: RuntimeCtx,
    server: String,
    mut payload: HashMap<String, serde_json::Value>,
) {
    /*
     * Randomized startup delay retained from your original benchmark.
     */
    std::thread::sleep(
        Duration::from_millis(3000) + Duration::from_millis(rand::rng().random_range(0..2000)),
    );

    let workload: Workload =
        serde_json::from_value(payload.remove("workload").expect("missing workload"))
            .expect("invalid workload");

    let config = WorkloadConfig::new(workload);

    assert!(
        config.concurrency > 0,
        "concurrency must be greater than zero"
    );

    assert!(
        !config.run_duration.is_zero(),
        "run_duration must be greater than zero"
    );

    let concurrency = config.concurrency;

    let addr = ctx.addr.to_string();

    let client_id = addr.rsplit('_').next().unwrap().to_string();

    BehaviourBuilder::new(
        Processor {
            start_time: None,
            client_id,
            config,

            request_factory: RequestFactory::new(addr.clone()),

            generated_requests: 0,
            completed_requests: 0,
            completed_within_run: 0,

            outstanding_requests: 0,

            generation_done: false,
            results_flushed: false,
        },
        BincodeCodec::default(),
    )
    .send(Sender::new(server))
    .generator_if(true, || WorkloadIterator::new(addr, concurrency))
    .on_send_failure(SendErrAction::Drop)
    .build()
    .run(ctx)
    .await
    .unwrap();

    println!("EXPERIMENT COMPLETED, YOU CAN EXIT NOW.");
}
